mac-test:
  stage: test
  before_script:
    - bundle install
  script:
    - bundle exec fastlane macos unit_test
  artifacts:
    paths:
      - xcov_output
  tags:
    - ios

pages:
  stage: deploy
  dependencies:
    - mac-test
  script:
    - mv xcov_output/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
  tags:
    - ios