FORMAT: 1A
HOST: https://example.com

# My API
## GET /message

+ Response 200 (text/plain)

        Hello World!

+ Response 200 (text/plain)

        Hello World2!

## POST /message2

+ Response 204 (text/plain)

        Hello World!
