# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Tests for iOS"
  lane :unit_test do
    scan(
      scheme: "Jellyfish-iOS",
      xcargs: 'HOST_URL="http://127.0.0.1"'
    )
    xcov(
      scheme: "Jellyfish-iOS",
      output_directory: "xcov_report"
    )
  end
end

platform :macos do
  desc "Tests for macOS"
  lane :unit_test do
    scan(
      scheme: "Jellyfish-macOS",
      xcargs: 'HOST_URL="http://127.0.0.1"'
    )
    xcov(
      scheme: "Jellyfish-macOS",
      output_directory: "xcov_report"
    )
  end
end